language: node_js
os: linux
dist: xenial

env:
  - MBX_CI_DOMAIN=o619qyc20d.execute-api.us-east-1.amazonaws.com
before_install:
  - curl -Ls https://mapbox-release-engineering.s3.amazonaws.com/mbx-ci/latest/mbx-ci-linux-amd64 > mbx-ci && chmod 755 ./mbx-ci
  - ./mbx-ci npm token --write-file

node_js:
  - "6"
  - "8"
  - "10"

script:
  - npm run lint
  - npm test
